### ISSUE TITLE
파일정보 받아오기 함수 pull과정에서 충돌발생

### ISSUE THREAD

**Issue by duswl9801** [jjhttoz/Assignment2#15]
error: Your local changes to the following files would be overwritten by merge:
	main.c
Please, commit your changes or stash them before you can merge.
Aborting
이런 메세지와 함께 충돌 발생 오류가 떴습니다.

**Comment by jjhttoz** [comment]
git stash 명령어를 입력하면 됩니다.

**Comment by ChoiJuEon** [comment]
https://gist.github.com/ihoneymon/652be052a0727ad59601
위키 문법 자료입니다.
